name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: asthabomble

      - name: Push SVG
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
